name: Deploy to AWS EC2

on:
  push:
    branches:
      - AI-Warehouse-Backend-Hung

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Kết nối SSH vào AWS và chạy lệnh Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/EXE201-BE
            
            git pull origin AI-Warehouse-Backend-Hung  
            
            cd backend
            
            chmod +x mvnw
            ./mvnw clean package -DskipTests    
            
            docker compose down
            docker compose up -d --build